language: python
python:
 - "3.6"

sudo: required

services:
  - docker

install:
  - sudo docker pull httpd:2.4
  - pip install -r requirements.txt
  - sudo docker-compose build
  - sudo docker-compose up &
  - while ! (curl -k --silent --head http://localhost:5000); do sleep 1; done
  - sleep 10

script:
  - pytest test/test.py
